-- create parent tables

CREATE TABLE author
(
    author_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_name     VARCHAR(30) UNIQUE,
    author_img_path varchar(50)
);

CREATE TABLE chord
(
    chord_id       INT PRIMARY KEY,
    chord_name     VARCHAR(10) UNIQUE,
    chord_img_path VARCHAR(50)
);

CREATE TABLE difficult_level
(
    difficult_level_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    difficult_level_name     VARCHAR(10) UNIQUE,
    difficult_level_img_path VARCHAR(50)
);

CREATE TABLE genre
(
    genre_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    genre_name     VARCHAR(15) UNIQUE,
    genre_img_path VARCHAR(50)
);

CREATE TABLE tuning_instrument
(
    tuning_id   INT PRIMARY KEY,
    tuning_name VARCHAR(10) UNIQUE
);

CREATE TABLE languages
(
    language_id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    language_name        VARCHAR(15) UNIQUE,
    language_img_path VARCHAR(50)
);

CREATE TABLE section_type
(
    section_type_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_type_name VARCHAR(6) UNIQUE,
    section_type_img_path VARCHAR(50)
);

CREATE TABLE strumming_pattern
(
    strumming_pattern_id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    strumming_pattern_name     VARCHAR(20) UNIQUE,
    strumming_pattern_img_path VARCHAR(50)
);

-- create main table - song

CREATE TABLE song
(
    song_id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_post_date     TIMESTAMP,
    song_lyrics        TEXT,
    song_comments      TEXT,
    song_name          VARCHAR(20),
    author_id          INT REFERENCES author (author_id),
    difficult_level_id INT REFERENCES difficult_level (difficult_level_id),
    section_type_id    INT REFERENCES section_type (section_type_id),
    tuning_id          INT REFERENCES tuning_instrument (tuning_id)
);

-- create many-to-many tables

CREATE TABLE song_chords
(
    song_id    INT REFERENCES song (song_id),
    chord_id INT REFERENCES chord (chord_id)
);

CREATE TABLE song_genre
(
    song_id  INT REFERENCES song (song_id),
    genre_id INT REFERENCES genre (genre_id)
);

CREATE TABLE song_language
(
    song_id     INT REFERENCES song (song_id),
    language_id INT REFERENCES languages (language_id)
);

CREATE TABLE song_strumming_pattern
(
    song_id              INT REFERENCES song (song_id),
    strumming_pattern_id INT REFERENCES strumming_pattern (strumming_pattern_id)
);