CREATE TABLE post
(
    post_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id   INT REFERENCES model.song (song_id) UNIQUE,
    user_id   INT REFERENCES user_schema.user_form (user_id),
    views     INT DEFAULT 0,
    post_date TIMESTAMP
);

CREATE TABLE comments
(
    comment_id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id      INT REFERENCES post (post_id),
    comment      TEXT,
    user_id      INT REFERENCES user_schema.user_form (user_id),
    comment_date TIMESTAMP
);

